const dataDepositProduct =
{
    "success": true,
    "message": "List of Deposit Products",
    "data": {
        "depositProd": [
            {
                "id": 1,
                "name": "Simpanan Daun",
                "prefix": "BGS",
                "description": "In publishing and graphic design, Lorem ipsum is a placeholder text commonly used to demonstrate the visual form of a document or a typeface without relying on meaningful content. Lorem ipsum may be used as a placeholder before final copy is available",
                "interest_rate": 0.02,
                "interest_calculation": "flat",
                "compound": "daily",
                "posting": "monthly",
                "digit_after_decimal": 6,
                "in_multiple_of": "100",
                "lock_in_value": 2,
                "lock_in_period": "monthly",
                "tax": "pph23 1.2",
                "theme_color": "FFF975",
                "created_by": "GPR-2-0001",
                "created_at": "2021-02-02T20:13:35.000Z",
                "updated_at": "2021-02-02T20:13:35.000Z",
                "id_deposit_prod": "SMPN-01-0001",
                "deposit_type": "fixed"
            },
            {
                "id": 2,
                "name": "Simpanan Gajah",
                "prefix": "ADT",
                "description": "In publishing and graphic design, Lorem ipsum is a placeholder text commonly used to demonstrate the visual form of a document or a typeface without relying on meaningful content. Lorem ipsum may be used as a placeholder before final copy is available",
                "interest_rate": 0.02,
                "interest_calculation": "flat",
                "compound": "daily",
                "posting": "monthly",
                "digit_after_decimal": 6,
                "in_multiple_of": "100",
                "lock_in_value": 2,
                "lock_in_period": "monthly",
                "tax": "pph23 1.2",
                "theme_color": "75FFA4",
                "created_by": "GPR-2-0001",
                "created_at": "2021-02-08T07:03:03.000Z",
                "updated_at": "2021-02-08T07:03:03.000Z",
                "id_deposit_prod": "SMPN-01-0002",
                "deposit_type": "fixed"
            },
            {
                "id": 3,
                "name": "Simpanan Masa depan",
                "prefix": "DZA",
                "description": "In publishing and graphic design, Lorem ipsum is a placeholder text commonly used to demonstrate the visual form of a document or a typeface without relying on meaningful content. Lorem ipsum may be used as a placeholder before final copy is available",
                "interest_rate": 0.02,
                "interest_calculation": "flat",
                "compound": "daily",
                "posting": "monthly",
                "digit_after_decimal": 6,
                "in_multiple_of": "100",
                "lock_in_value": 2,
                "lock_in_period": "monthly",
                "tax": "pph23 1.2",
                "theme_color": "75EEFF",
                "created_by": "GPR-2-0001",
                "created_at": "2021-02-08T07:03:14.000Z",
                "updated_at": "2021-02-08T07:03:14.000Z",
                "id_deposit_prod": "SMPN-01-0003",
                "deposit_type": "fixed"
            },
            {
                "id": 4,
                "name": "Simpanan Masa Tua",
                "prefix": "NSA",
                "description": "In publishing and graphic design, Lorem ipsum is a placeholder text commonly used to demonstrate the visual form of a document or a typeface without relying on meaningful content. Lorem ipsum may be used as a placeholder before final copy is available",
                "interest_rate": 0.02,
                "interest_calculation": "flat",
                "compound": "daily",
                "posting": "monthly",
                "digit_after_decimal": 6,
                "in_multiple_of": "100",
                "lock_in_value": 2,
                "lock_in_period": "monthly",
                "tax": "pph23 1.2",
                "theme_color": "FF4F37",
                "created_by": "GPR-2-0001",
                "created_at": "2021-02-08T07:03:29.000Z",
                "updated_at": "2021-02-08T07:03:29.000Z",
                "id_deposit_prod": "SMPN-01-0004",
                "deposit_type": "fixed"
            },
            {
                "id": 5,
                "name": "Simpanan Nikah",
                "prefix": "ALU",
                "description": "In publishing and graphic design, Lorem ipsum is a placeholder text commonly used to demonstrate the visual form of a document or a typeface without relying on meaningful content. Lorem ipsum may be used as a placeholder before final copy is available",
                "interest_rate": 0.02,
                "interest_calculation": "flat",
                "compound": "daily",
                "posting": "monthly",
                "digit_after_decimal": 6,
                "in_multiple_of": "100",
                "lock_in_value": 2,
                "lock_in_period": "monthly",
                "tax": "pph23 1.2",
                "theme_color": "7594FF",
                "created_by": "GPR-2-0001",
                "created_at": "2021-02-08T07:03:45.000Z",
                "updated_at": "2021-02-08T07:03:45.000Z",
                "id_deposit_prod": "SMPN-01-0005",
                "deposit_type": "fixed"
            },
            {
                "id": 6,
                "name": "Simpanan Untuk Anak-Anak",
                "prefix": "OBD",
                "description": "In publishing and graphic design, Lorem ipsum is a placeholder text commonly used to demonstrate the visual form of a document or a typeface without relying on meaningful content. Lorem ipsum may be used as a placeholder before final copy is available",
                "interest_rate": 0.02,
                "interest_calculation": "flat",
                "compound": "daily",
                "posting": "monthly",
                "digit_after_decimal": 6,
                "in_multiple_of": "100",
                "lock_in_value": 2,
                "lock_in_period": "monthly",
                "tax": "pph23 1.2",
                "theme_color": "FF75E9",
                "created_by": "GPR-2-0001",
                "created_at": "2021-02-08T07:04:05.000Z",
                "updated_at": "2021-02-08T07:04:05.000Z",
                "id_deposit_prod": "SMPN-01-0006",
                "deposit_type": "fixed"
            }
        ]
    },
    "options": {
        "pageInfo": {
            "page": 1,
            "totalPage": 2,
            "perPage": 3,
            "totalData": 6,
            "nextLink": "http://192.168.100.7:6464/product?limit=3&page=2&search=&sort=asc&type=depo",
            "prevLink": null
        }
    }
}

export default dataDepositProduct;